version: '3.8'

services:
  model_service:
    build: ./model-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./model-service/:/app/
    container_name: model_service

  recsys_interface_service:
    build: ./recsys-interface-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8001
    volumes:
      - ./recsys-interface-service/:/app/
    container_name: recsys_interface_service

  nginx:
    build: ./nginx-service
    container_name: nginx_service
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-service/nginx_config.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-service/cert/dev_cert.pem:/etc/nginx/cert/dev_cert.pem
      - ./nginx-service/cert/dev_key.pem:/etc/nginx/cert/dev_key.pem
    depends_on:
      - model_service
      - recsys_interface_service